language: node_js
node_js:
  - "node"
notifications:
  email:
    on_failure: change
    on_success: never
install:
  - yarn install
script:
  - jest --coverage --coverageReporters=text-lcov | coveralls
    