language: node_js
node_js:
  - "node"
notifications:
  email:
    on_failure: change
    on_success: never
install:
  - yarn install
script:
  - yarn test --coverage
deploy:
  provider: heroku
  api_key:
    secure: HEROKU_API