language: node_js
services:
  - docker
node_js:
  - "12"
notifications:
  email:
    on_failure: change
    on_success: never
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - docker-compose run bot
before_deploy:
  - yarn build
# Define the release stage that runs semantic-release
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn release
