language: node_js
sudo: required
addons:
  postgresql: "10"
node_js:
  - "node"
notifications:
  email:
    on_failure: change
    on_success: never
cache:
  directories:
    - node_modules/
install:
  - yarn install
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - yarn test
  - npx codecov
