language: node_js
node_js:
  - "node"
notifications:
  email:
    on_failure: change
    on_success: never
cache:
  directories:
  - node_modules/
install:
  - yarn install
script:
  - yarn test --coverage --coverageReporters=text-lcov | coveralls
before_deploy:
  - yarn build
deploy:
  local_dir: 'lib/'
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  target-branch: build
  on:
    branch: master