import { Collection, User } from "discord.js";
import { IDatabase } from "pg-promise";
import Cog from "./cog";
export declare const getDateFromArgs: (args: string[]) => string | undefined;
export declare const isInDatabase: (authorId: number, result: any[]) => boolean;
export declare const isDuplicateEntry: (authorId: number, date: string, result: any[]) => boolean;
export declare const updateEntry: (authorId: number, date: string, result: Record<string, any>[], db: IDatabase<any, import("pg-promise/typescript/pg-subset").IClient>) => Promise<"Added new entry!" | "Updated entry!" | "Name and date already in the database, so I'm not gonna re-add it.">;
export declare const listUsers: (result: any, users: Collection<string, User>) => string;
declare const BirthdayCog: Cog;
export default BirthdayCog;
