import { Collection, Snowflake, User } from "discord.js";
import { IDatabase } from "pg-promise";
import Cog from "./cog";
export declare const getDateFromArgs: (args: Array<string>) => string | undefined;
export declare const isInDatabase: (authorId: number, result: Array<any>) => boolean;
export declare const isDuplicateEntry: (authorId: number, date: string, result: Array<any>) => boolean;
export declare const updateEntry: (authorId: number, date: string, result: Array<Record<string, any>>, db: IDatabase<any>) => Promise<"Added new entry!" | "Updated entry!" | "Name and date already in the database, so I'm not gonna re-add it.">;
export declare const listUsers: (result: any, users: Collection<Snowflake, User>) => string;
declare const BirthdayCog: Cog;
export default BirthdayCog;
